/*
KB Script


*/

SELECT 
	CUSTOMERSCHOLARSHIP.CUSTOMER_ID
	, Charges.CHARGE_NAME
	, CUSTOMERSCHOLARSHIPDISCOUNT.PERCENTAGE
FROM CUSTOMERSCHOLARSHIP
	JOIN CUSTOMERS
		ON CUSTOMERS.CUSTOMER_ID = CUSTOMERSCHOLARSHIP.CUSTOMER_ID
	LEFT JOIN Charges 
		ON Charges.CHARGE_ID = CUSTOMERSCHOLARSHIP.CHARGE_ID 
	LEFT JOIN CUSTOMERSCHOLARSHIPDISCOUNT
		ON CUSTOMERSCHOLARSHIPDISCOUNT.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
WHERE 
	1=1

GROUP BY 
	CUSTOMERSCHOLARSHIP.CUSTOMER_ID
	, Charges.CHARGE_NAME
	, CUSTOMERSCHOLARSHIPDISCOUNT.PERCENTAGE



